name: SubsystemFarmwelt
version: ${project.version}
main: me.maximilian1021.main.Main
api-version: 1.16
authors: [ Maximilian1021 ]
description: Regelt die Funktionen und Permission auf der Farmwelt
website: https://max1021.de

commands:
  Spawn:
    description: Teleportiert dich zum Weltspawnpunkt
